name: backport-command
on:
  repository_dispatch:
    types: [backport-command]
jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray

      - name: Get assignees
        env:
          ASSIGNEES: ${{ toJson(github.event.client_payload.github.payload.issue.assignees) }}
        id: assignees
        run: echo ::set-output name=assignees::$(echo "$ASSIGNEES" | jq -r '.[].login' | paste -s -d ',' -)

      - name: Get branch
        env:
          BRANCH: ${{ toJson(github.event.client_payload.slash_command.args.unnamed.arg1) }}
        id: branch
        run: echo ::set-output name=branch::"$BRANCH"

      - name: Get latest milestone
        id: milestone
        run: |
          major=$(echo "${{ toJson(github.event.client_payload.slash_command.args.unnamed.arg1) }}" | grep -Eo '^(v[0-9][0-9].[0-9][0-9])')
          echo ::set-output name=milestone::$(curl -1sfL -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.ACTIONS_BOT_TOKEN }}" \
            https://api.github.com/repos/${{ toJson(github.event.client_payload.slash_command.args.named.repo) }}/milestones | jq -r .[].title | grep ${major} | sort | tail -n 1)

      - name: output
        run: echo ${{ steps.assignees.outputs.assignees }}

      - name: output
        run: echo ${{ steps.branch.outputs.branch }}

      - name: output
        run: echo ${{ toJson(github.event.client_payload.slash_command.args.named.repo) }}

      - name: output
        run: echo ${{ steps.milestone.outputs.milestone }}

      - name: Install gh cli
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Create issue
        run: |
          gh auth login --with-token <<< "${{ secrets.ACTIONS_BOT_TOKEN }}"
          gh issue create --title "Backport ${{ toJson(github.event.client_payload.github.payload.issue.title) }} to ${{ steps.branch.outputs.branch }}" \
            --repo "${{ toJson(github.event.client_payload.slash_command.args.named.repo) }}" \
            --assignee "${{ steps.assignees.outputs.assignees }}" \
            --milestone "${{ steps.milestone.outputs.milestone }}" \
            --body "issue: ${{ toJson(github.event.client_payload.github.payload.comment.issue_url) }}"
