on:
  issue_comment:
    types: [created]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo ${{ toJson(github.event.comment.user.login) }}
      - name: test
        if: |
          github.event.comment.user.login == 'gousteris'
        run: echo y
